### ISSUE TITLE
Question about WalletConnect v2.0 migration schedule

### ISSUE THREAD

**Issue by EthanYa** [vu3th/vue-dapp#116]
Hi,

I noticed that the WalletConnect package has a migration schedule for version 2.0 and it's not backwards-compatible with version 1.0. I was wondering if the maintainers have any plans to upgrade the package and coordinate a migration schedule to ensure that end-users do not suffer from this transition?

Reference:
- https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e
- https://docs.walletconnect.com/2.0/advanced/migrating-from-v1.0

**Comment by chnejohnson** [comment]
Cool, I planned to create a new connector named WalletConnectorV2 for this migration. This issue has not yet been started so welcome any contributors to jump in and make your mark :)

**Comment by chnejohnson** [comment]
Starting from v0.9.x, WalletConnect v2 is supported.
