### ISSUE TITLE
Connecting... screen gets stuck when Metamask is not automatically triggered.

### ISSUE THREAD

**Issue by re2005** [vu3th/vue-dapp#117]
Hey people here, I'm having a few reports about users getting stuck on this this screen:

<img width="1654" alt="Screenshot 2023-01-24 at 09 45 23" src="https://user-images.githubusercontent.com/2920357/214295016-cce3cb5a-54e6-4f8c-ba8d-b4f80b37e6d7.png">

This is screens is shown when users click on connect and `Metamask` is triggered to unlock/connect etc...

Somehow sometimes `Metamask` doesn't show up (is not triggered) and VueDapp gets stuck on this screen.

Perhaps we can set a timeout so the APP unstuck itself?

Does anyone else recon this issue ?

@chnejohnson please let me know anything.

Thanks!

**Comment by chnejohnson** [comment]
@re2005 I will look into this problem as soon as possible.

**Comment by re2005** [comment]
Hey @chnejohnson I believe that users with a heavy `Metamask` are facing this issue.

Since Vue-Dapp blocks the entire page with the Modal:

See:
https://github.com/chnejohnson/vue-dapp/blob/main/src/components/Board.vue#L128

We may should have some sort of timeout, or make it so the entire UI gets stuck.
https://github.com/chnejohnson/vue-dapp/blob/main/src/components/Board.vue#L65

Users are reporting that they are stuck on that screen, seems like the APP sends the signal to metamask to connect, but metamask never replies it and the APP gets into the limbo.

Alternatives: 
- Set a timeout for the `isAutoConnecting` to be back to false
- Make that entire loading modal optional
- We also need to think about the connecting button to also not get stuck.

Cheers.

**Comment by re2005** [comment]
There is a related issue to this one:

Please check:
https://github.com/MetaMask/metamask-extension/issues/17339

Here on the MetaMask Connector:
https://github.com/chnejohnson/vue-dapp/blob/main/src/connectors/metaMask.ts#L99

The method `connect` is not wrapped into a `try` and it seems that MetaMask is not returning anything in this case, so it may be the way Vue-Dapp is handling it ?

Really appreciate any help here.

**Comment by chnejohnson** [comment]
@re2005 Hi, I added a timeout when requesting to MetaMask. Not sure how to reproduce the situation for this issue, can you help me check if this #125 can tackle the problem?

**Comment by chnejohnson** [comment]
Close this issue as vue-dapp has introduced a new version with breaking changes. If there is an issue, please open a new one.
