### ISSUE TITLE
Reconnecting does not work on Rabby wallet

### ISSUE THREAD

**Issue by tempe-techie** [vu3th/vue-dapp#121]
Rabby wallet is an alternative to MetaMask. It uses (almost) the same API, so you can connect with Rabby wallet through the MetaMask connector in Vue Dapp.

But when reloading the site, the reconnect feature does not work for Rabby. The error in the console says: "No auto-connect to MetaMask: not connected".

Any idea how to solve this? 🙂 How does Vue Dapp currently remember a MetaMask connection? 🤔

P.S.: There are some other wallets that also use the same API as MetaMask (e.g. Bifrost mobile wallet), but suffer from the same reconnecting issue as Rabby.

**Comment by tempe-techie** [comment]
Nevermind, I managed to get this functionality via a custom modal for connectors and handling auto connections through local storage 🙂

**Comment by chnejohnson** [comment]
@tempe-techie thanks for reporting this problem. Let's let the issue be open

**Comment by chnejohnson** [comment]
Close this issue as vue-dapp has introduced a new version with breaking changes. Now it supports EIP-6963, this problem will probably be solved.
