### ISSUE TITLE
WalletConnect v2 support

### ISSUE THREAD

**Issue by re2005** [vu3th/vue-dapp#129]
Seems like we a using a deprecated version of `WalletConnect`

We should use `@walletconnect/web3wallet`

**Comment by re2005** [comment]
Before June 28
https://docs.walletconnect.com/2.0/advanced/migration-from-v1.x/overview

**Comment by chnejohnson** [comment]
@re2005 Got it. Will prepare to migrate to the new version before the expiration date

**Comment by re2005** [comment]
Awesome, I've tried quickly to make it work. Lots of typing and other stuff to fix:
https://github.com/vu3th/vue-dapp/pull/133

Also don't see `metamask` option in here.

**Comment by chnejohnson** [comment]
FYI https://github.com/clrfund/monorepo/pull/657/files

**Comment by chnejohnson** [comment]
@re2005 Hey, thanks for starting PR #133 and helping with the testing. You're amazing! To show my appreciation, I'd like to sponsor you with 10 DAI from the funds we collected for vue-dapp. Just give me your ETH address and let me know which network you prefer for the transaction. Once I have that, I'll take care of the reward. Thanks again for your awesome contributions to vue-dapp!

**Comment by chnejohnson** [comment]
@re2005 Hey, thanks for starting PR #133 and helping with the testing. To show my appreciation, I'd like to sponsor you with `10 DAI` from the funds we collected for vue-dapp. All you need to provide is your ETH address and let me know which network you prefer for the transaction (Ethereum or Polygon). Once I have that, I'll take care of the reward. Thank you for your contributions!

**Comment by tempe-techie** [comment]
@re2005 great job! 😎 I can also send you some DAI if you provide the address 🤘

**Comment by re2005** [comment]
@chnejohnson @tempe-techie I really appreciate it. Will DM @chnejohnson with the `0x..`
Once again thanks, I'm looking forward to keep improving this lib!

**Comment by goums** [comment]
Thanks @re2005 ❤️ & @chnejohnson for adding WalletConnect v2 support
We just integrated it, but came across few issues, so I'm sharing here our workarounds.

It seems that `EthereumProviderOptions` is expecting `rpcMap` and not `rpc`, see here:
https://www.npmjs.com/package/@walletconnect/ethereum-provider 
Maybe `rpc` was in an older version?

We had to updates these 2 lines to replace `rpc` with `rpcMap`:
- https://github.com/vu3th/vue-dapp/blob/cd4df362e29445f130940cac7ac1f6879d600af5/src/connectors/walletConnect.ts#L89
- https://github.com/vu3th/vue-dapp/blob/cd4df362e29445f130940cac7ac1f6879d600af5/src/connectors/walletConnect.ts#L111



Also, the `onChainChanged` receives an hex value for the chainId, see here:
https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/providers/ethereum-provider/src/EthereumProvider.ts#L425

So we had to replace this line: https://github.com/vu3th/vue-dapp/blob/cd4df362e29445f130940cac7ac1f6879d600af5/src/connectors/walletConnect.ts#L88
with: 
```ts
this.#provider.on('chainChanged', (hexChainId: string) => {
    const chainId = parseInt(hexChainId, 16);
```

**Comment by chnejohnson** [comment]
@goums Nice! I will fix it. Thanks for your sharing!
