### ISSUE TITLE
Connection Stuck when new window or returning to website

### ISSUE THREAD

**Issue by re2005** [vu3th/vue-dapp#130]
Hey @chnejohnson This is the bug I've been dealing with for more than 6 months now.

I was able to capture in a recording so you can also see what is going on.

https://github.com/vu3th/vue-dapp/assets/2920357/f0153be3-fdef-42a8-b3ad-106cb56cf243

**Comment by chnejohnson** [comment]
Close this issue as vue-dapp has introduced a new version with breaking changes.
