### ISSUE TITLE
Update WalletConnect dependencies

### ISSUE THREAD

**Issue by tempe-techie** [vu3th/vue-dapp#144]
When I try to connect via WalletConnect (through VueDapp), I see that the connector is trying to use the deprecated v1 URL:

```
https://rpc.walletconnect.com/v1/?chainId=eip155:...
```

I [searched a bit](https://github.com/WalletConnect/walletconnect-monorepo/issues/2789#issuecomment-1614634755) and it may be that WalletConnect libraries in VueDapp's package.json need to be updated. @chnejohnson Can you please do that?

**Comment by chnejohnson** [comment]
@tempe-techie Got it. I will look into this

**Comment by tempe-techie** [comment]
I'm guessing this issue has been fixed with the `@vue-dapp/walletconnect` package, right?

**Comment by chnejohnson** [comment]
@tempe-techie Yes, that's right.
