### ISSUE TITLE
npm installation fails

### ISSUE THREAD

**Issue by tempe-techie** [vu3th/vue-dapp#152]
When trying to install new Vue Dapp libraries using `npm install`, I get this error:

```bash
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:^
```

Installing with yarn works, though.

Can you try to reproduce the error?

**Comment by chnejohnson** [comment]
@tempe-techie Thanks, I noticed the problem. It will be resolved. Currently it works with `@vue-dapp/vd-board@1.0.0-beta-10`, but noted that there will be some significant changes on a new pull request.
