### ISSUE TITLE
ConnectError when connecting wallet using vue-dapp

### ISSUE THREAD

**Issue by MonsterKey** [vu3th/vue-dapp#155]
Describe the bug
A clear and concise description of what the bug is. When attempting to connect a wallet using the vue-dapp framework, an error is thrown, preventing the connection from being established.

To Reproduce

Go to '...'
Click on 'Connect Wallet'
See error in the console
Error Log
4958.94727034.js:1 Connect error: ConnectError: TypeError: Cannot read properties of null (reading '0')
at chunk-vendors.da31725e.js:24:93188
at Generator.next ()
at a (chunk-vendors.da31725e.js:24:77500)

Screenshots
<img width="666" alt="vue-dapp-error" src="https://github.com/vu3th/vue-dapp/assets/59218975/5f128a5d-1276-4d1e-83f3-e86d4855d772">

**Comment by chnejohnson** [comment]
Hi @MonsterKey, are you using vue-dapp and then running `pnpm dev` in the root directory to open the webpage?
