### ISSUE TITLE
Error connecting to a phantom wallet

### ISSUE THREAD

**Issue by coxlr** [vu3th/vue-dapp#158]
Is there anything additional that is needed to connect successfully to a phantom wallet?

I have run the example apps and they give me the same error as I get when implementing the code in my project.

When selecting Phantom from the VueDappModel it return the error message:

Failed to request MetaMask: Missing or invalid parameters.

I have also tested using a browser that only has the Phantom wallet extension installed and not metamask and still get the same error.

Using the example app here I get the same error: [https://vue-dapp.vercel.app/](https://vue-dapp.vercel.app/)

![Screenshot](https://github.com/vu3th/vue-dapp/assets/8451762/26f340ff-c319-4fe3-b104-ae3c16127793)

**Comment by johnson86tw** [comment]
@coxlr Got it, I reproduced the same error. Let me look into it

**Comment by johnson86tw** [comment]
@coxlr I fixed it in PR #159. You can now test it using @vue-dapp/core@1.1.0

**Comment by coxlr** [comment]
That looks like it has fixed it, thanks!
